"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import { useState } from "react";



const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [state, setstate] = useState(0);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar></Navbar>
        <div>Hello world {state}</div>
        <button onClick={() => setstate(state + 1)}>+</button>
        {children}
      </body>
    </html>
  );
}

